// This module's output (which slot times exist on a given date) is NOT
// secret -- BUSINESS.hours already renders publicly in the site footer, and
// the whole point of this module is that its result must reach the browser
// as availability data (rendered by a Server Component into a Client
// Component's props, per plan 04-06). No `import 'server-only'` fence is
// added here: unlike `pricing.ts` (which guards non-public pricing data),
// there is no secret to protect, and the decision matrix (D-01..D-03) is
// exactly as safe to compute in either environment. Every known caller in
// this phase (plan 04-05's Server Action re-validation, plan 04-06's Server
// Component month/day data fetch) is server-side regardless -- this module
// is dependency-free and pure, so it costs nothing to leave it importable
// from either side.

import { BUSINESS } from '@/lib/constants'

/**
 * D-01: length of a single bookable appointment slot, in minutes. Every slot
 * generated by `generateSlotsForDate` is exactly this long.
 */
export const SLOT_DURATION_MINUTES = 90

interface DayHours {
    openMinutes: number
    closeMinutes: number
}

/**
 * Resolves the given date's weekday to its matching `BUSINESS.hours` entry
 * and returns the open/close times in minutes-since-midnight, or `null` when
 * the business is closed that day (D-03: Sunday, or any future `closed: true`
 * entry -- there is no Sunday-specific branch here, only a lookup against the
 * single source of truth in `@/lib/constants`).
 *
 * @param date - The calendar date to resolve. Only its weekday matters.
 * @returns The day's open/close minutes, or `null` if closed.
 */
function resolveDayHours(date: Date): DayHours | null {
    const weekday = date.getDay() // 0 = Sunday .. 6 = Saturday

    // BUSINESS.hours uses the literal `days` strings 'Mon–Fri' (EN DASH,
    // U+2013 -- not an ASCII hyphen), 'Sat', 'Sun'. Match on those exact
    // literals rather than assuming an ASCII '-' would work.
    const entry = BUSINESS.hours.find((hoursEntry) => {
        if (hoursEntry.days === 'Sun') return weekday === 0
        if (hoursEntry.days === 'Sat') return weekday === 6
        if (hoursEntry.days === 'Mon–Fri') return weekday >= 1 && weekday <= 5
        return false
    })

    if (!entry || entry.closed || entry.open === null || entry.close === null) {
        return null
    }

    return {
        openMinutes: parseTwelveHourToMinutes(entry.open),
        closeMinutes: parseTwelveHourToMinutes(entry.close),
    }
}

/**
 * Parses a 12-hour clock string like `'8:00 AM'` or `'6:00 PM'` into
 * minutes-since-midnight.
 *
 * @param time - A 12-hour time string in the exact `'H:mm AM'`/`'H:mm PM'` shape used by `BUSINESS.hours`.
 * @returns The equivalent minutes-since-midnight (0-1439).
 */
function parseTwelveHourToMinutes(time: string): number {
    const [clockPart, meridiem] = time.split(' ')
    const [hourPart, minutePart] = clockPart.split(':')
    let hour = Number(hourPart)
    const minute = Number(minutePart)

    if (meridiem === 'PM' && hour !== 12) hour += 12
    if (meridiem === 'AM' && hour === 12) hour = 0

    return hour * 60 + minute
}

/**
 * Formats minutes-since-midnight as a zero-padded 24-hour `'HH:mm'` string.
 *
 * @param minutes - Minutes since midnight (0-1439).
 * @returns The `'HH:mm'` string, e.g. `90` -> `'01:30'`.
 */
function minutesToTimeString(minutes: number): string {
    const hour = Math.floor(minutes / 60)
    const minute = minutes % 60
    return `${String(hour).padStart(2, '0')}:${String(minute).padStart(2, '0')}`
}

/**
 * Generates the ordered list of legal appointment slot start times for the
 * given date, derived purely from `BUSINESS.hours` (D-03 -- never a
 * duplicated schedule table).
 *
 * D-02's rule is expressed as the general loop guard
 * `start + SLOT_DURATION_MINUTES <= closeMinutes`: a slot is offered only if
 * it ends at or before closing. This is why Saturday (9:00 AM-2:00 PM) yields
 * exactly three slots -- 9:00, 10:30, 12:00 -- and drops the 1:30 slot, which
 * would end at 3:00 PM, after the 2:00 PM close. That drop is a *consequence*
 * of the inequality, not a Saturday special case: any future edit to
 * `BUSINESS.hours` (a different close time, a new day's hours) is handled
 * correctly with no code change here.
 *
 * @param date - The calendar date to generate slots for. Only its weekday is used.
 * @returns An ordered array of `'HH:mm'` 24-hour slot start times. Empty when the business is closed that day.
 */
export function generateSlotsForDate(date: Date): string[] {
    const hours = resolveDayHours(date)
    if (hours === null) return []

    const slots: string[] = []
    for (
        let start = hours.openMinutes;
        start + SLOT_DURATION_MINUTES <= hours.closeMinutes;
        start += SLOT_DURATION_MINUTES
    ) {
        slots.push(minutesToTimeString(start))
    }

    return slots
}
